server {
    listen 80;
    server_name 8.137.114.176;

    # 后端 API 反向代理
    location ~ ^/(user|land|product|order|msg|alipay|resource)/ {
        proxy_pass http://backend:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_method $request_method;
        client_max_body_size 60m;
    }

    # 前端静态文件
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
