version: '1.0'
name: cloudland-deploy
displayName: Cloudland Auto Deploy

triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - main

stages:
  - name: deploy
    displayName: Deploy To Aliyun
    executor:
      - t1longlive
    steps:
      - type: deploy@agent
        name: deploy_server
        displayName: Run Remote Deploy Script
        hostGroupID:
          id: ali_cloudland
          ids:
            - 844d9abd-3fd6-4e32-99ee-3339f2497a55
        script:
          - cd /root/cloudland
          - git fetch origin main
          - git checkout main
          - git reset --hard origin/main
          - chmod +x scripts/deploy.sh
          - /bin/bash scripts/deploy.sh main
