version: '1.0'
name: cloudland-deploy
displayName: cloudland-deploy
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - main
stages:
  - name: deploy
    displayName: Deploy To Aliyun
    strategy: naturally
    trigger: auto
    executor:
      - t1longlive
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        schedulerType: DISTRIBUTED
        hostGroupID:
          ID: ali_cloudland
          hostID:
            - 844d9abd-3fd6-4e32-99ee-3339f2497a55
        scriptType: SH
        script:
          - cd /root/cloudland
          - git fetch origin main
          - git checkout main
          - git reset --hard origin/main
          - /bin/bash scripts/deploy.sh main
        gitClone: false
        notify: []
        strategy:
          retry: '0'
